/**
 * NocoBase collection definitions — import via Admin UI or migration plugin.
 * Maps to PostgreSQL tables created by migrate_to_postgres.py
 */
export const collections = [
  {
    name: 'tickets',
    title: 'Support Tickets',
    fields: [
      { name: 'ticket_id', type: 'string', unique: true },
      { name: 'subject', type: 'string', required: true },
      { name: 'description', type: 'text' },
      { name: 'category', type: 'string' },
      { name: 'priority', type: 'string', defaultValue: 'medium' },
      { name: 'status', type: 'string', defaultValue: 'open' },
      { name: 'assigned_to', type: 'string' },
      { name: 'assigned_to_name', type: 'string' },
      { name: 'created_by', type: 'string', required: true },
      { name: 'created_by_name', type: 'string' },
      { name: 'created_by_type', type: 'string' },
      { name: 'tehsil_id', type: 'string' },
      { name: 'district_id', type: 'string' },
      { name: 'state_id', type: 'string' },
      { name: 'resolved_at', type: 'date' },
      { name: 'resolution_time_seconds', type: 'integer' },
      { name: 'satisfaction_rating', type: 'integer' },
    ],
  },
  {
    name: 'ticket_comments',
    title: 'Ticket Comments',
    fields: [
      { name: 'ticket_id', type: 'string' },
      { name: 'author_id', type: 'string' },
      { name: 'author_name', type: 'string' },
      { name: 'author_role', type: 'string' },
      { name: 'message', type: 'text', required: true },
      { name: 'is_internal', type: 'boolean', defaultValue: false },
    ],
  },
  {
    name: 'vendors',
    title: 'Vendors',
    fields: [
      { name: 'vendor_id', type: 'string', unique: true, primaryKey: true },
      { name: 'business_name', type: 'string', required: true },
      { name: 'business_type', type: 'string' },
      { name: 'gst_number', type: 'string' },
      { name: 'address', type: 'text' },
      { name: 'tehsil_id', type: 'string' },
      { name: 'verification_status', type: 'string', defaultValue: 'pending' },
      { name: 'average_rating', type: 'float', defaultValue: 0 },
      { name: 'total_ratings', type: 'integer', defaultValue: 0 },
    ],
  },
  {
    name: 'products',
    title: 'Products',
    fields: [
      { name: 'vendor_id', type: 'string' },
      { name: 'name', type: 'string', required: true },
      { name: 'description', type: 'text' },
      { name: 'price', type: 'integer' },
      { name: 'unit', type: 'string' },
      { name: 'stock_available', type: 'integer' },
      { name: 'is_available', type: 'boolean', defaultValue: true },
      { name: 'image_url', type: 'string' },
      { name: 'category', type: 'string' },
    ],
  },
  {
    name: 'orders',
    title: 'Orders',
    fields: [
      { name: 'order_id', type: 'string', unique: true },
      { name: 'buyer_private_id', type: 'string' },
      { name: 'buyer_name', type: 'string' },
      { name: 'buyer_address', type: 'text' },
      { name: 'buyer_tehsil_id', type: 'string' },
      { name: 'items', type: 'json' },
      { name: 'subtotal', type: 'integer' },
      { name: 'delivery_charge', type: 'integer' },
      { name: 'total_amount', type: 'integer' },
      { name: 'delivery_agent_id', type: 'string' },
      { name: 'order_status', type: 'string' },
      { name: 'payment_status', type: 'string' },
      { name: 'payment_method', type: 'string' },
      { name: 'delivered_at', type: 'date' },
    ],
  },
  {
    name: 'ratings',
    title: 'Ratings',
    fields: [
      { name: 'order_id', type: 'string' },
      { name: 'rater_private_id', type: 'string' },
      { name: 'rated_private_id', type: 'string' },
      { name: 'rating_type', type: 'string' },
      { name: 'rating_value', type: 'integer' },
      { name: 'comment', type: 'text' },
    ],
  },
];
